name = "joinflipfluence"
compatibility_date = "2024-03-20"

[build]
command = "npm run build"
publish = ".next"

[site]
Bucket = ".next/static"
entry-point = "workers-site/index.js"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
route = "joinflipfluence.pages.dev"

[env.staging]
name = "joinflipfluence-staging"
route = "staging.joinflipfluence.pages.dev"